name: BlockInfo
version: 1.0.0
api-version: 1.13
description: "Stores and gets informations about who placed and broke blocks."
author: oscardoras
main: me.oscardoras.blockinfo.BlockInfoPlugin
permissions:
  blockinfo:
    default: op
    children:
      blockinfo.command: true
  blockinfo.command:
    default: op
    children:
      blockinfo.command.blockinfo: true
  blockinfo.command.blockinfo:
    default: op